# .github/workflows/z03-link-apple-isrc-to-spotify.yml
name: zzzzz_99999_link-apple-isrc-to-spotify

on:
  workflow_dispatch:

jobs:
  link-isrc:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v5

      - name: 🐍 Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: 📦 Install deps
        run: pip install -r requirements.txt

      - name: 🔗 Link ISRC → Spotify
        env:
          # Spotify (same as your other jobs)
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REDIRECT_URI: ${{ secrets.SPOTIFY_REDIRECT_URI }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

          # Postgres
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

          # Tuning (optional)
          ISRC_LINK_LIMIT: "1000"   # rows per batch per run
          ISRC_LINK_SLEEP: "0.10"   # seconds between requests
          ISRC_LINK_MARKET: "US"
        run: PYTHONPATH=. python apple_private/link_isrc_to_spotify.py